#!/usr/bin/env bash
# install-jam-service.sh - install the systemd unit for the Jamboree
# orchestrator supervisor.
#
# The unit launches `process-compose up -f process-compose.yaml` as the
# maestro user. This is the load-bearing decision for runtime security:
# without it, process-compose runs as root, the silently-ignored `user:`
# directive on each service leaves them as root too, and every per-task
# artifact (worktree admin dirs, NATS state, journal files) ends up
# root-owned. Verified empirically that v1.40.1 ignores the `user:`
# directive entirely; see
# ~/.claude/projects/-home-caleb-jamboree/memory/project_process_compose_user_directive_bug.md.
#
# Idempotent. Writes a unit file under /etc/systemd/system/, reloads,
# and (optionally) enables + starts. Re-running with the same Cargo
# version is a no-op.
#
# Usage:
#   sudo ./scripts/install-jam-service.sh            # install + reload
#   sudo ./scripts/install-jam-service.sh --enable    # also enable on boot
#   sudo ./scripts/install-jam-service.sh --start     # also start now
#   sudo ./scripts/install-jam-service.sh --dry-run

set -euo pipefail

UNIT_PATH="/etc/systemd/system/jam.service"
COMPOSE_PATH_DEFAULT="/home/caleb/jamboree/process-compose.yaml"
PROCESS_COMPOSE_BIN_DEFAULT="/opt/jam/bin/process-compose"
SOCK_PATH_DEFAULT="/home/maestro/.jam/process-compose.sock"
MAESTRO_USER="${JAM_MAESTRO_USER:-maestro}"

DRY_RUN=0
ENABLE=0
START=0
COMPOSE_PATH="$COMPOSE_PATH_DEFAULT"
PROCESS_COMPOSE_BIN="$PROCESS_COMPOSE_BIN_DEFAULT"
SOCK_PATH="$SOCK_PATH_DEFAULT"

pass() { printf '  \x1b[32m✓\x1b[0m %s\n' "$1"; }
info() { printf '  \x1b[36m∼\x1b[0m %s\n' "$1"; }
warn() { printf '  \x1b[33m!\x1b[0m %s\n' "$1" >&2; }
die() {
    printf '  \x1b[31m✗\x1b[0m %s\n' "$1" >&2
    if [[ $# -ge 2 ]] && [[ -n "${2:-}" ]]; then
        printf '\n    Fix:\n'
        printf '%s\n' "$2" | sed 's/^/    /' >&2
    fi
    exit "${3:-1}"
}

require_root() {
    if [[ $EUID -ne 0 ]]; then
        die "must run as root (writes /etc/systemd/system/jam.service)" \
"sudo $0 $*" 64
    fi
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --dry-run) DRY_RUN=1; shift ;;
            --enable)  ENABLE=1; shift ;;
            --start)   START=1; shift ;;
            --compose) COMPOSE_PATH="$2"; shift 2 ;;
            --bin)     PROCESS_COMPOSE_BIN="$2"; shift 2 ;;
            --sock)    SOCK_PATH="$2"; shift 2 ;;
            --help|-h) sed -n '2,22p' "$0" | sed 's/^# //; s/^#//'; exit 0 ;;
            *) die "unknown argument: $1" "See $0 --help." 64 ;;
        esac
    done
}

preflight() {
    if [[ ! -x "$PROCESS_COMPOSE_BIN" ]]; then
        die "process-compose binary not found at $PROCESS_COMPOSE_BIN" \
"Run install-substrate.sh first, or pass --bin <path>." 65
    fi
    if [[ ! -f "$COMPOSE_PATH" ]]; then
        die "process-compose.yaml not found at $COMPOSE_PATH" \
"Pass --compose <path> to point at the right monorepo." 65
    fi
    if ! id "$MAESTRO_USER" >/dev/null 2>&1; then
        die "user '$MAESTRO_USER' does not exist" \
"Run bootstrap-users.sh first." 65
    fi
    if ! command -v systemctl >/dev/null 2>&1; then
        die "systemctl not found" \
"This script assumes systemd. Use the legacy launch path instead." 65
    fi
    pass "preflight"
}

render_unit() {
    cat <<UNIT
# Auto-generated by scripts/install-jam-service.sh. Do not edit by hand;
# changes will be overwritten on the next run. To customize, pass flags
# to install-jam-service.sh or edit the script itself.

[Unit]
Description=Jamboree orchestrator (process-compose supervisor)
Documentation=https://github.com/cleak/jamboree
# NATS uses the loopback interface; no network-online needed.
After=network.target
Wants=network.target

[Service]
Type=simple
User=$MAESTRO_USER
Group=$MAESTRO_USER

# Run process-compose in foreground so systemd owns the process lifecycle.
# -t=false disables the TUI; we attach via the unix socket instead.
ExecStart=$PROCESS_COMPOSE_BIN \\
    -U -u $SOCK_PATH \\
    up -f $COMPOSE_PATH \\
    -t=false

# Clean shutdown via process-compose's own teardown.
ExecStop=$PROCESS_COMPOSE_BIN -U -u $SOCK_PATH down

# Pickers can be CPU-intensive (cargo build, codex inference). Don't kill
# children when this unit restarts — process-compose will reap them, and
# the worktree per-task isolation means an orphan one cycle isn't fatal.
KillMode=mixed
TimeoutStopSec=60

# Linger across user-session disconnects; the orchestrator must keep
# running when caleb logs out of his shell.
RemainAfterExit=no
Restart=on-failure
RestartSec=5

# Maestro's HOME and a sane PATH so spawned children find tools.
# Mirror the process-compose.yaml top-level \`environment:\` block.
Environment=HOME=/home/$MAESTRO_USER
Environment=JAM_HOME=/home/$MAESTRO_USER/.jam
Environment=NATS_URL=nats://127.0.0.1:4222
Environment=PATH=/home/$MAESTRO_USER/.npm-global/bin:/home/$MAESTRO_USER/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

[Install]
WantedBy=multi-user.target
UNIT
}

install_unit() {
    local tmp
    tmp="$(mktemp)"
    trap 'rm -f "$tmp"' RETURN
    render_unit > "$tmp"

    if [[ -f "$UNIT_PATH" ]] && cmp -s "$tmp" "$UNIT_PATH"; then
        pass "jam.service already up to date: $UNIT_PATH"
        return
    fi

    if [[ $DRY_RUN -eq 1 ]]; then
        info "[dry-run] would write $UNIT_PATH:"
        sed 's/^/    /' "$tmp" >&2
        return
    fi

    install -m 0644 -o root -g root "$tmp" "$UNIT_PATH"
    pass "installed $UNIT_PATH"
    systemctl daemon-reload
    pass "systemctl daemon-reload"
}

maybe_enable() {
    [[ $ENABLE -eq 1 ]] || return 0
    if [[ $DRY_RUN -eq 1 ]]; then
        info "[dry-run] would systemctl enable jam.service"
        return
    fi
    systemctl enable jam.service >/dev/null
    pass "enabled jam.service for boot"
}

maybe_start() {
    [[ $START -eq 1 ]] || return 0
    if [[ $DRY_RUN -eq 1 ]]; then
        info "[dry-run] would systemctl start jam.service"
        return
    fi
    # Caller is responsible for stopping any pre-existing root-launched
    # process-compose before starting the unit. Detect the conflict and
    # warn loudly rather than racing.
    if pgrep -af '/opt/jam/bin/process-compose .* up' >/dev/null 2>&1; then
        warn "a process-compose instance is already running; not auto-stopping it"
        warn "stop it manually before invoking --start, e.g.:"
        warn "  sudo $PROCESS_COMPOSE_BIN -U -u $SOCK_PATH down"
        return
    fi
    systemctl start jam.service
    pass "started jam.service"
}

main() {
    parse_args "$@"
    require_root "$@"
    printf '\x1b[1mJamboree systemd unit installer\x1b[0m\n\n'
    preflight
    install_unit
    maybe_enable
    maybe_start
    printf '\n\x1b[32mdone\x1b[0m\n'
    cat <<'NEXT'

Next steps:

  1. Verify the unit file:
       systemctl cat jam.service

  2. (If you weren't already running process-compose) start it:
       sudo systemctl start jam.service
       sudo systemctl enable jam.service   # auto-start on boot

  3. Restart paths:
       sudo systemctl restart jam.service   # full restart
       sudo systemctl stop jam.service      # graceful shutdown
       journalctl -u jam.service -f         # tail logs
NEXT
}

main "$@"
