#!/usr/bin/env python3
"""Generate Rust types and JSON schemas from `crates/jam-events/events.toml`.

Per `dec-events-toml-manifest` and spec §4.4.3: events.toml is the single source
of truth. This script generates:

  - crates/jam-events/src/generated/types.rs       (Rust structs + Event trait)
  - crates/jam-events/src/generated/schemas/*.json (JSON Schema, one per event)

Pydantic models for the Python Maestro land in maestro/src/jam_maestro/events/
once the Python package exists (Phase 1).

Run modes:
    python3 tools/events-codegen.py            # regenerate
    python3 tools/events-codegen.py --check    # exit 1 if regen would change anything

Pre-commit hook should invoke `--check`. CI re-runs on every PR (per `comp-pre-commit-hooks`).

Type mapping:
    string       -> String
    u32, u64     -> u32, u64
    f64          -> f64
    bool         -> bool
    datetime     -> chrono::DateTime<chrono::Utc>
    trace_id     -> jam_trace::TraceId  (also accepted as String at deserialization)
    path         -> String              (kept simple; events are wire data, not filesystem ops)
    duration_ms  -> u64

Field requirements:
    required = false  -> wrapped in Option<T>; serde skips serialization when None.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
EVENTS_TOML = REPO_ROOT / "crates" / "jam-events" / "events.toml"
GENERATED_DIR = REPO_ROOT / "crates" / "jam-events" / "src" / "generated"
TYPES_RS = GENERATED_DIR / "types.rs"
SCHEMAS_DIR = GENERATED_DIR / "schemas"

GENERATED_HEADER = """\
// AUTO-GENERATED by tools/events-codegen.py from crates/jam-events/events.toml.
// DO NOT EDIT BY HAND. Re-run the codegen script to update.
//
// Per `dec-events-toml-manifest` (spec §4.4.3): events.toml is the single
// source of truth. CI verifies this file is in sync via `--check`.
"""

# ─── Type mapping ──────────────────────────────────────────────────────

RUST_TYPE_MAP = {
    "string": "String",
    "u32": "u32",
    "u64": "u64",
    "f64": "f64",
    "bool": "bool",
    "datetime": "chrono::DateTime<chrono::Utc>",
    "trace_id": "jam_trace::TraceId",
    "path": "String",
    "duration_ms": "u64",
}

JSON_TYPE_MAP = {
    "string": ("string", None),
    "u32": ("integer", {"minimum": 0, "maximum": 4294967295}),
    "u64": ("integer", {"minimum": 0}),
    "f64": ("number", None),
    "bool": ("boolean", None),
    "datetime": ("string", {"format": "date-time"}),
    "trace_id": ("string", {"pattern": "^[0-9A-HJKMNP-TV-Z]{26}$"}),
    "path": ("string", None),
    "duration_ms": ("integer", {"minimum": 0}),
}


# ─── Manifest parsing ──────────────────────────────────────────────────


@dataclass
class Field:
    name: str
    rust_type_base: str
    required: bool

    @property
    def rust_type(self) -> str:
        base = RUST_TYPE_MAP[self.rust_type_base]
        return base if self.required else f"Option<{base}>"

    @property
    def serde_attrs(self) -> list[str]:
        if self.required:
            return []
        # Skip serializing None so envelope JSONL matches the spec's compact shape.
        return ['serde(skip_serializing_if = "Option::is_none")']


@dataclass
class Event:
    name: str  # e.g. "picker.spawned"
    version: int
    description: str
    fields: list[Field]

    @property
    def struct_name(self) -> str:
        # "picker.spawned" -> "PickerSpawned"
        # "pr.review-received" -> "PrReviewReceived"
        parts = re.split(r"[.\-]", self.name)
        return "".join(part.capitalize() for part in parts if part)


def load_manifest() -> tuple[int, list[Event]]:
    """Read events.toml. Returns (schema_version, events)."""
    with EVENTS_TOML.open("rb") as f:
        doc = tomllib.load(f)

    schema_version = int(doc.get("schema_version", 1))
    events_section = doc.get("events", {})

    events: list[Event] = []
    for name, body in events_section.items():
        if not isinstance(body, dict):
            raise SystemExit(f"events.toml: events.{name!r} is not a table")

        version = int(body.get("version", 1))
        description = body.get("description", "")
        raw_fields = body.get("fields", [])

        fields: list[Field] = []
        for entry in raw_fields:
            field_name = entry.get("name")
            field_type = entry.get("type")
            required = bool(entry.get("required", False))

            if not field_name or not field_type:
                raise SystemExit(
                    f"events.toml: events.{name!r} field missing name or type: {entry!r}"
                )
            if field_type not in RUST_TYPE_MAP:
                raise SystemExit(
                    f"events.toml: events.{name!r} field {field_name!r} "
                    f"has unknown type {field_type!r}. "
                    f"Valid types: {', '.join(sorted(RUST_TYPE_MAP))}"
                )

            fields.append(Field(name=field_name, rust_type_base=field_type, required=required))

        events.append(Event(name=name, version=version, description=description, fields=fields))

    # Sort for deterministic output.
    events.sort(key=lambda e: e.name)
    return schema_version, events


# ─── Rust generation ───────────────────────────────────────────────────


def generate_rust(schema_version: int, events: list[Event]) -> str:
    # Build a list of single-line strings (no trailing newlines).
    # `"\n".join(...) + "\n"` at the bottom produces fmt-clean output:
    # exactly one trailing newline, single blank line between sections.
    out: list[str] = list(GENERATED_HEADER.rstrip().splitlines())
    out.append("")
    out.append("#![allow(clippy::module_name_repetitions)]")
    out.append("")
    out.append("use serde::{Deserialize, Serialize};")
    out.append("")
    out.append("/// Manifest schema version (from events.toml).")
    out.append(f"pub const MANIFEST_SCHEMA_VERSION: u32 = {schema_version};")
    out.append("")
    out.append("/// Common shape implemented by every generated event payload.")
    out.append("///")
    out.append("/// Provides compile-time access to the event type identifier and")
    out.append("/// `event_subtype_version` so call sites cannot accidentally use the wrong")
    out.append("/// version when constructing an envelope.")
    out.append("pub trait Event: Serialize + serde::de::DeserializeOwned {")
    out.append('    /// Kebab-case dotted event type (e.g. `"picker.spawned"`).')
    out.append("    const EVENT_TYPE: &'static str;")
    out.append("    /// Per-event-type version, bumped on additive changes only.")
    out.append("    const EVENT_SUBTYPE_VERSION: u32;")
    out.append("}")

    for event in events:
        out.append("")
        out.extend(_generate_struct(event))

    return "\n".join(out) + "\n"


def _generate_struct(event: Event) -> list[str]:
    """Render struct + impl. Caller is responsible for blank-line separators."""
    out: list[str] = []
    if event.description:
        out.append(f"/// {event.description}")
        out.append("///")
    out.append(f"/// Event type: `{event.name}` (version {event.version}).")
    out.append("#[derive(Debug, Clone, Serialize, Deserialize)]")
    out.append(f"pub struct {event.struct_name} {{")
    for field in event.fields:
        for attr in field.serde_attrs:
            out.append(f"    #[{attr}]")
        out.append(f"    pub {field.name}: {field.rust_type},")
    out.append("}")
    out.append("")
    out.append(f"impl Event for {event.struct_name} {{")
    out.append(f'    const EVENT_TYPE: &\'static str = "{event.name}";')
    out.append(f"    const EVENT_SUBTYPE_VERSION: u32 = {event.version};")
    out.append("}")
    return out


# ─── JSON Schema generation ────────────────────────────────────────────


def generate_json_schema(event: Event) -> dict:
    properties: dict[str, dict] = {}
    required: list[str] = []
    for field in event.fields:
        json_type, extras = JSON_TYPE_MAP[field.rust_type_base]
        prop: dict = {"type": json_type}
        if extras:
            prop.update(extras)
        properties[field.name] = prop
        if field.required:
            required.append(field.name)

    schema: dict = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"jam-events:{event.name}",
        "title": event.name,
        "type": "object",
        "additionalProperties": False,
        "properties": properties,
    }
    if event.description:
        schema["description"] = event.description
    if required:
        schema["required"] = required
    return schema


# ─── File writing ──────────────────────────────────────────────────────


def write_files(rust_src: str, schemas: dict[str, dict], check_only: bool) -> int:
    """Write or compare generated files. Returns nonzero exit code on mismatch in --check mode."""
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    SCHEMAS_DIR.mkdir(parents=True, exist_ok=True)

    drift: list[str] = []

    if not _file_matches(TYPES_RS, rust_src):
        if check_only:
            drift.append(str(TYPES_RS.relative_to(REPO_ROOT)))
        else:
            TYPES_RS.write_text(rust_src)

    # Track existing schema files so we can prune renamed/removed events.
    existing = {p.name for p in SCHEMAS_DIR.glob("*.json")}
    expected: set[str] = set()
    for event_name, schema in schemas.items():
        filename = f"{event_name}.json"
        expected.add(filename)
        path = SCHEMAS_DIR / filename
        rendered = json.dumps(schema, indent=2, sort_keys=False) + "\n"
        if not _file_matches(path, rendered):
            if check_only:
                drift.append(str(path.relative_to(REPO_ROOT)))
            else:
                path.write_text(rendered)

    stale = existing - expected
    for stale_name in sorted(stale):
        path = SCHEMAS_DIR / stale_name
        if check_only:
            drift.append(f"{path.relative_to(REPO_ROOT)} (stale; would be removed)")
        else:
            path.unlink()

    if check_only and drift:
        print("events-codegen: out of sync. Run `python3 tools/events-codegen.py` to regen:", file=sys.stderr)
        for path in drift:
            print(f"  {path}", file=sys.stderr)
        return 1

    return 0


def _file_matches(path: Path, content: str) -> bool:
    return path.exists() and path.read_text() == content


# ─── Main ──────────────────────────────────────────────────────────────


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if generated files are out of sync with events.toml.",
    )
    args = parser.parse_args()

    schema_version, events = load_manifest()
    rust_src = generate_rust(schema_version, events)
    schemas = {event.name: generate_json_schema(event) for event in events}

    rc = write_files(rust_src, schemas, check_only=args.check)
    if not args.check:
        print(f"events-codegen: regenerated {len(events)} events -> types.rs + {len(schemas)} schemas")
    return rc


if __name__ == "__main__":
    sys.exit(main())
